base_config_file: /root/autodl-tmp/outputs/minimal_sf_stage4_6_multi_scene_v7/experiment002/config.yaml

model:
  stage: '4_6'

data:
  assets:
    root: /root/autodl-tmp/streetforward_assets_pt120w

dataset:
  pointcloud:
    near_max_points: 400000
    distant_max_points: 800000

batch_eval:
  enable: true
  output_dir: /root/autodl-tmp/outputs/batch_eval_v7_stage4_6
  data_mode: segment_finetune_train

  checkpoint:
    path: "/root/autodl-tmp/outputs/minimal_sf_stage4_6_multi_scene_v7/experiment002/checkpoints/minimal_sf_stage4_6_multi_scene_v7_step50000.pt"
    strict: true

  dataset:
    scene_ids: [10, 140, 194, 142, 114, 121]
    segment_policy: all
    require_full_window: true
    stride: 30
    max_episodes_per_scene: null
    max_total_episodes: null
    window_policy: sliding

  cameras:
    ids: [0, 1, 2, 3, 4, 5]
    names: ["front", "front_left", "front_right", "back_left", "back_right", "back"]

  runtime:
    mode: segment_finetune_train
    no_grad: false
    amp: false
    reset_state_per_episode: true
    align_with_scheduler_v7: true
    align_with_scheduler_v8: false
    update_node_state: true
    update_hidden_state: true
    update_view_transient: true
    block_order: block_major
    step_major_switch_interval_steps: 1
    reset_policy: block_end
    target_frame_policy: scheduler_v7_block_window
    max_target_frames_including_source: 3

  sky_eval:
    enable: false

  history:
    update_step_norm_ema: true
    record_support_residual_on_input_exit: false
    record_each_step: false

  render:
    save_pre_update: true
    save_each_iter_views: false
    save_png: true
    save_video: false
    save_numpy: false
    save_depth_or_acc: false

  metrics:
    primary_mask: full_image
    report_full_image: true
    compute_psnr: true
    compute_ssim: true
    compute_lpips: false
    compute_l1: true
    min_valid_pixels: 32

  experiments:
    - name: exp_v7_5_3_stage4_6
      sequence_length: 5
      input_offsets: [0, 1, 2]
      eval_offsets: all
      steps_per_input: 8
